<?php if (!empty($flash)): ?>
<p style="color: green"><?= $flash['success'][0] ?></p>
<?php endif; ?>
<form action="<?= $router->urlFor('index.users') ?>" method="get">
    <label>Search for user:</label>
    <input type="search" id="term" name="term" value="<?= htmlspecialchars($term) ?>" />
    <button type="submit">Search</button>
</form>

<hr>
<?php if (empty($users)): ?>
    <p>Nothing to display. :(</p>
<?php endif; ?>
<ul>
    <?php foreach ($users as $id => $user): ?>
        <li><a href="<?= $router->urlFor('show.user', ['nickname' => $user['nickname'], 'id' => $user['id']]) ?>"><?= htmlspecialchars($user['nickname']) ?></a></li>
    <?php endforeach; ?>
</ul>