<form action="<?= $router->urlFor('create.user') ?>" method="post">
    <div>
        <h1>New User</h1>
        <hr>
    </div>
    <div>
        <label>
            Nickname:
            <input type="text" name="user[nickname]" value="<?= htmlspecialchars($user['nickname'])?>">
        </label>
        <?php if (isset($errors['nickname'])): ?>
            <div style="color: red;"><?= htmlspecialchars($errors['nickname']) ?></div>
        <?php endif; ?>
    </div>
    <div>
        <label>
            Email:
            <input type="email" name="user[email]" value="<?= htmlspecialchars($user['email'])?>">
        </label>
    </div>
    <input type="submit" value="Sign Up">
</form>